$primary    = rgb({{colors.primary.dark.hex_stripped}})
$background = rgb({{colors.background.dark.hex_stripped}})
$surface    = rgb({{colors.surface.dark.hex_stripped}})
$on_primary = rgb({{colors.on_primary.dark.hex_stripped}})
