require("core")
require("plugins")
-- vim.cmd("colorscheme nightfox")
vim.cmd("colorscheme carbonfox")
-- vim.cmd("colorscheme tokyonight")
-- Dedizierte Neovim-Python-Umgebung (nie wechseln)
vim.g.python3_host_prog = vim.fn.expand("~/miniforge3/envs/neovim/bin/python")
