# Enable focus events for Vim autoread
set-option -g focus-events on

# Enable True color support
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:RGB"

# Allow passthrough escape sequences
set -g allow-passthrough on

set -g base-index 1
set -g pane-base-index 1

# Prefix
unbind C-b
set -g prefix C-b
set -g prefix2 none

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Splits
unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Copy Mode
unbind v
bind v copy-mode

# Pane navigation
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# maximize panes
bind -r m resize-pane -Z

# mouse support
set -g mouse on

# vim shell navigations and selects in tmux panes
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

# Instant switch to a new tmux session directory that exist
bind-key -r f run-shell "tmux neww ~/.config/tmux/tmux-sessionsizer"
bind-key n command-prompt "new-session -s '%%'"

# Drag copy using mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# TPM (tmux plugin manager)
set-environment -g TMUX_PLUGIN_MANAGER_PATH ~/.config/tmux/.tmux/plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"

set -g @sessionx-bind 'o'
set -g @resurrect-capture-pane-contents "on"
set -g @continuum-restore "on"

# Configure Online status
set -g @online_icon "ok"
set -g @offline_icon "nok"

# Status bar
set -g status-position bottom
set -g status-style "bg=#{@thm_bg}"
set -g status-justify "centre"

# status left look and feel
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_bg},bold]  #S },#{#[bg=#{@thm_bg},fg=#{@thm_green}]  #S }}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]#{?window_zoomed_flag,│,}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_yellow}]#{?window_zoomed_flag,  zoom ,}"

# status right look and feel
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_blue}] 󰭦 %d-%m-%Y 󰅐 %H:%M "

# Windows look and feel
set -wg automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"

set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "bg=#{@thm_bg},fg=#{@thm_rosewater}"
set -g window-status-last-style "bg=#{@thm_bg},fg=#{@thm_peach}"
set -g window-status-activity-style "bg=#{@thm_red},fg=#{@thm_bg}"
set -g window-status-bell-style "bg=#{@thm_red},fg=#{@thm_bg},bold"
set -gF window-status-separator "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}]│"

set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=#{@thm_peach},fg=#{@thm_bg},bold"

run '~/.config/tmux/plugins/tpm/tpm' # always keep this line last
