
$background = rgb(0f1416)
$background_hex = #0f1416

$error = rgb(ffece9)
$error_hex = #ffece9

$error_container = rgb(ffaea4)
$error_container_hex = #ffaea4

$inverse_on_surface = rgb(000000)
$inverse_on_surface_hex = #000000

$inverse_primary = rgb(004f62)
$inverse_primary_hex = #004f62

$inverse_surface = rgb(dee3e6)
$inverse_surface_hex = #dee3e6

$on_background = rgb(dee3e6)
$on_background_hex = #dee3e6

$on_error = rgb(000000)
$on_error_hex = #000000

$on_error_container = rgb(000000)
$on_error_container_hex = #000000

$on_primary = rgb(000000)
$on_primary_hex = #000000

$on_primary_container = rgb(000000)
$on_primary_container_hex = #000000

$on_primary_fixed = rgb(000000)
$on_primary_fixed_hex = #000000

$on_primary_fixed_variant = rgb(00141b)
$on_primary_fixed_variant_hex = #00141b

$on_secondary = rgb(000000)
$on_secondary_hex = #000000

$on_secondary_container = rgb(000000)
$on_secondary_container_hex = #000000

$on_secondary_fixed = rgb(000000)
$on_secondary_fixed_hex = #000000

$on_secondary_fixed_variant = rgb(00141b)
$on_secondary_fixed_variant_hex = #00141b

$on_surface = rgb(ffffff)
$on_surface_hex = #ffffff

$on_surface_variant = rgb(ffffff)
$on_surface_variant_hex = #ffffff

$on_tertiary = rgb(000000)
$on_tertiary_hex = #000000

$on_tertiary_container = rgb(000000)
$on_tertiary_container_hex = #000000

$on_tertiary_fixed = rgb(000000)
$on_tertiary_fixed_hex = #000000

$on_tertiary_fixed_variant = rgb(0c0e2c)
$on_tertiary_fixed_variant_hex = #0c0e2c

$outline = rgb(e9f1f6)
$outline_hex = #e9f1f6

$outline_variant = rgb(bcc4c8)
$outline_variant_hex = #bcc4c8

$primary = rgb(dbf4ff)
$primary_hex = #dbf4ff

$primary_container = rgb(84cde8)
$primary_container_hex = #84cde8

$primary_fixed = rgb(b7eaff)
$primary_fixed_hex = #b7eaff

$primary_fixed_dim = rgb(88d1ec)
$primary_fixed_dim_hex = #88d1ec

$scrim = rgb(000000)
$scrim_hex = #000000

$secondary = rgb(dcf4fe)
$secondary_hex = #dcf4fe

$secondary_container = rgb(afc6d0)
$secondary_container_hex = #afc6d0

$secondary_fixed = rgb(cfe6f1)
$secondary_fixed_hex = #cfe6f1

$secondary_fixed_dim = rgb(b3cad4)
$secondary_fixed_dim_hex = #b3cad4

$shadow = rgb(000000)
$shadow_hex = #000000

$source_color = rgb(787e81)
$source_color_hex = #787e81

$surface = rgb(0f1416)
$surface_hex = #0f1416

$surface_bright = rgb(4b5153)
$surface_bright_hex = #4b5153

$surface_container = rgb(2c3134)
$surface_container_hex = #2c3134

$surface_container_high = rgb(373c3f)
$surface_container_high_hex = #373c3f

$surface_container_highest = rgb(42484a)
$surface_container_highest_hex = #42484a

$surface_container_low = rgb(1b2023)
$surface_container_low_hex = #1b2023

$surface_container_lowest = rgb(000000)
$surface_container_lowest_hex = #000000

$surface_dim = rgb(0f1416)
$surface_dim_hex = #0f1416

$surface_tint = rgb(88d1ec)
$surface_tint_hex = #88d1ec

$surface_variant = rgb(40484c)
$surface_variant_hex = #40484c

$tertiary = rgb(f0eeff)
$tertiary_hex = #f0eeff

$tertiary_container = rgb(bfbfe7)
$tertiary_container_hex = #bfbfe7

$tertiary_fixed = rgb(e0e0ff)
$tertiary_fixed_hex = #e0e0ff

$tertiary_fixed_dim = rgb(c3c3eb)
$tertiary_fixed_dim_hex = #c3c3eb


