
$background = rgb(0f1416)
$background_hex = #0f1416

$error = rgb(ffece9)
$error_hex = #ffece9

$error_container = rgb(ffaea4)
$error_container_hex = #ffaea4

$inverse_on_surface = rgb(000000)
$inverse_on_surface_hex = #000000

$inverse_primary = rgb(004f5f)
$inverse_primary_hex = #004f5f

$inverse_surface = rgb(dee3e6)
$inverse_surface_hex = #dee3e6

$on_background = rgb(dee3e6)
$on_background_hex = #dee3e6

$on_error = rgb(000000)
$on_error_hex = #000000

$on_error_container = rgb(000000)
$on_error_container_hex = #000000

$on_primary = rgb(000000)
$on_primary_hex = #000000

$on_primary_container = rgb(000000)
$on_primary_container_hex = #000000

$on_primary_fixed = rgb(000000)
$on_primary_fixed_hex = #000000

$on_primary_fixed_variant = rgb(001419)
$on_primary_fixed_variant_hex = #001419

$on_secondary = rgb(000000)
$on_secondary_hex = #000000

$on_secondary_container = rgb(000000)
$on_secondary_container_hex = #000000

$on_secondary_fixed = rgb(000000)
$on_secondary_fixed_hex = #000000

$on_secondary_fixed_variant = rgb(001419)
$on_secondary_fixed_variant_hex = #001419

$on_surface = rgb(ffffff)
$on_surface_hex = #ffffff

$on_surface_variant = rgb(ffffff)
$on_surface_variant_hex = #ffffff

$on_tertiary = rgb(000000)
$on_tertiary_hex = #000000

$on_tertiary_container = rgb(000000)
$on_tertiary_container_hex = #000000

$on_tertiary_fixed = rgb(000000)
$on_tertiary_fixed_hex = #000000

$on_tertiary_fixed_variant = rgb(090e2c)
$on_tertiary_fixed_variant_hex = #090e2c

$outline = rgb(e9f1f5)
$outline_hex = #e9f1f5

$outline_variant = rgb(bbc4c8)
$outline_variant_hex = #bbc4c8

$primary = rgb(d8f5ff)
$primary_hex = #d8f5ff

$primary_container = rgb(81cee4)
$primary_container_hex = #81cee4

$primary_fixed = rgb(b0ecff)
$primary_fixed_hex = #b0ecff

$primary_fixed_dim = rgb(85d1e8)
$primary_fixed_dim_hex = #85d1e8

$scrim = rgb(000000)
$scrim_hex = #000000

$secondary = rgb(dbf4fd)
$secondary_hex = #dbf4fd

$secondary_container = rgb(aec7cf)
$secondary_container_hex = #aec7cf

$secondary_fixed = rgb(cee7ef)
$secondary_fixed_hex = #cee7ef

$secondary_fixed_dim = rgb(b2cbd3)
$secondary_fixed_dim_hex = #b2cbd3

$shadow = rgb(000000)
$shadow_hex = #000000

$source_color = rgb(0f1517)
$source_color_hex = #0f1517

$surface = rgb(0f1416)
$surface_hex = #0f1416

$surface_bright = rgb(4b5153)
$surface_bright_hex = #4b5153

$surface_container = rgb(2c3133)
$surface_container_hex = #2c3133

$surface_container_high = rgb(373c3e)
$surface_container_high_hex = #373c3e

$surface_container_highest = rgb(42484a)
$surface_container_highest_hex = #42484a

$surface_container_low = rgb(1b2022)
$surface_container_low_hex = #1b2022

$surface_container_lowest = rgb(000000)
$surface_container_lowest_hex = #000000

$surface_dim = rgb(0f1416)
$surface_dim_hex = #0f1416

$surface_tint = rgb(85d1e8)
$surface_tint_hex = #85d1e8

$surface_variant = rgb(40484b)
$surface_variant_hex = #40484b

$tertiary = rgb(efeeff)
$tertiary_hex = #efeeff

$tertiary_container = rgb(bcc0e7)
$tertiary_container_hex = #bcc0e7

$tertiary_fixed = rgb(dee0ff)
$tertiary_fixed_hex = #dee0ff

$tertiary_fixed_dim = rgb(c0c4eb)
$tertiary_fixed_dim_hex = #c0c4eb


