
$background = rgb(10140f)
$background_hex = #10140f

$error = rgb(ffece9)
$error_hex = #ffece9

$error_container = rgb(ffaea4)
$error_container_hex = #ffaea4

$inverse_on_surface = rgb(000000)
$inverse_on_surface_hex = #000000

$inverse_primary = rgb(245125)
$inverse_primary_hex = #245125

$inverse_surface = rgb(e0e4db)
$inverse_surface_hex = #e0e4db

$on_background = rgb(e0e4db)
$on_background_hex = #e0e4db

$on_error = rgb(000000)
$on_error_hex = #000000

$on_error_container = rgb(000000)
$on_error_container_hex = #000000

$on_primary = rgb(000000)
$on_primary_hex = #000000

$on_primary_container = rgb(000000)
$on_primary_container_hex = #000000

$on_primary_fixed = rgb(000000)
$on_primary_fixed_hex = #000000

$on_primary_fixed_variant = rgb(001602)
$on_primary_fixed_variant_hex = #001602

$on_secondary = rgb(000000)
$on_secondary_hex = #000000

$on_secondary_container = rgb(000000)
$on_secondary_container_hex = #000000

$on_secondary_fixed = rgb(000000)
$on_secondary_fixed_hex = #000000

$on_secondary_fixed_variant = rgb(061406)
$on_secondary_fixed_variant_hex = #061406

$on_surface = rgb(ffffff)
$on_surface_hex = #ffffff

$on_surface_variant = rgb(ffffff)
$on_surface_variant_hex = #ffffff

$on_tertiary = rgb(000000)
$on_tertiary_hex = #000000

$on_tertiary_container = rgb(000000)
$on_tertiary_container_hex = #000000

$on_tertiary_fixed = rgb(000000)
$on_tertiary_fixed_hex = #000000

$on_tertiary_fixed_variant = rgb(001417)
$on_tertiary_fixed_variant_hex = #001417

$outline = rgb(ecf2e6)
$outline_hex = #ecf2e6

$outline_variant = rgb(bec5b9)
$outline_variant_hex = #bec5b9

$primary = rgb(c9fec1)
$primary_hex = #c9fec1

$primary_container = rgb(9dd097)
$primary_container_hex = #9dd097

$primary_fixed = rgb(bcf0b5)
$primary_fixed_hex = #bcf0b5

$primary_fixed_dim = rgb(a0d39a)
$primary_fixed_dim_hex = #a0d39a

$scrim = rgb(000000)
$scrim_hex = #000000

$secondary = rgb(e3f5dc)
$secondary_hex = #e3f5dc

$secondary_container = rgb(b6c8b0)
$secondary_container_hex = #b6c8b0

$secondary_fixed = rgb(d5e8cf)
$secondary_fixed_hex = #d5e8cf

$secondary_fixed_dim = rgb(b9ccb4)
$secondary_fixed_dim_hex = #b9ccb4

$shadow = rgb(000000)
$shadow_hex = #000000

$source_color = rgb(284827)
$source_color_hex = #284827

$surface = rgb(10140f)
$surface_hex = #10140f

$surface_bright = rgb(4d514b)
$surface_bright_hex = #4d514b

$surface_container = rgb(2d322c)
$surface_container_hex = #2d322c

$surface_container_high = rgb(383d36)
$surface_container_high_hex = #383d36

$surface_container_highest = rgb(444841)
$surface_container_highest_hex = #444841

$surface_container_low = rgb(1c211b)
$surface_container_low_hex = #1c211b

$surface_container_lowest = rgb(000000)
$surface_container_lowest_hex = #000000

$surface_dim = rgb(10140f)
$surface_dim_hex = #10140f

$surface_tint = rgb(a0d39a)
$surface_tint_hex = #a0d39a

$surface_variant = rgb(424940)
$surface_variant_hex = #424940

$tertiary = rgb(c9f8fe)
$tertiary_hex = #c9f8fe

$tertiary_container = rgb(9dcbd0)
$tertiary_container_hex = #9dcbd0

$tertiary_fixed = rgb(bcebf1)
$tertiary_fixed_hex = #bcebf1

$tertiary_fixed_dim = rgb(a0cfd4)
$tertiary_fixed_dim_hex = #a0cfd4


