# always refer to Hyprland wiki
# https://wiki.hyprland.org/

$config = $HOME/.config/hypr/hyprland
source = colors.conf

source = $config/autostart.conf

source = $config/envs.conf
source = $config/looknfeel.conf
source = $config/windowrules.conf
source = $config/input.conf
source = $config/plugins.conf

source = $config/bindings.conf

source= $config/monitors.conf
source= $config/workspaces.conf

# HyprMod managed settings
# source = /home/Horro/.config/hypr/hyprland-gui.conf
