# always refer to Hyprland wiki
# https://wiki.hyprland.org/

$old = $HOME/.config/hypr/old
$config = $HOME/.config/hypr/hyprland
source = colors.conf

source = $old/autostart.conf

source = $old/envs.conf
source = $old/looknfeel.conf
source = $old/windowrules.conf
source = $old/input.conf
source = $old/plugins.conf

source = $old/bindings.conf

source= $old/monitors.conf
source= $old/workspaces.conf

# HyprMod managed settings
# source = /home/Horro/.config/hypr/hyprland-gui
