require("hyprland.autostart")
require("hyprland.envs")
require("hyprland.lookandfeel")
require("hyprland.windowrules")
require("hyprland.binds")
require("hyprland.input")
require("hyprland.monitors")
