# plugin = ~/.local/share/hyprpm/repos/split-monitor-workspaces/split-monitor-workspaces.so
plugin {
  split-monitor-workspace {
    count = 10
    keep_focused = true
    enable_notification = true
    link_monitors = true

  }
}
